### ISSUE TITLE
Various upgrade issues

### ISSUE THREAD

**Issue by dannyrb** [chafey/cornerstoneTools#221]
I've noticed new releases for cornerstone and its companion tool project:

- `cornerstone-core` (0.12.1) (previously 0.11.0)
- `cornerstone-tools` (0.9.0) (previously 0.8.9)

It may be worth noting that I load images using the `cornerstone-web-image-loader` package.

When I run `npm install cornerstone-tools@0.9.0 --save`, at runtime I get the following error:

> element is not enabled

Thinking I need to update to the latest `cornerstone-core`  to resolve the issue, I run `npm install cornerstone-core@0.12.1 --save`, but I see the following error at runtime:

> loadImageFromImageLoader: no image loader for imageId

No other changes. Only package updates. If I revert, delete node_modules, and restore all packages, I am able to continue development.

Any/all help is appreciated.

**Comment by dannyrb** [comment]
I'm not entirely sure why the above changes created new errors, but I was able to resolve the issue by adding the following:

```
cornerstone.registerImageLoader('http', cornerstoneWebImageLoader.loadImage);
cornerstone.registerImageLoader('https', cornerstoneWebImageLoader.loadImage);
```

It might be worth noting that I'm using Webpack + VueJS, and I'm firing the above lines in my viewer component's created hook.

**Comment by swederik** [comment]
I think this has now been fixed with the dependency injection work. You would need to add this somewhere, though:

````javascript
cornerstoneWebImageLoader.external.cornerstone = cornerstone;
````

**Comment by shashith** [comment]
Hi I experienced the same issue.

This is the list of libraries I used with there versions.
  "dependencies": {
    "cornerstone": "^0.1.1",
    "cornerstone-core": "^2.2.2",
    "cornerstone-math": "^0.1.6",
    "cornerstone-tools": "^2.3.3",
    "cornerstone-wado-image-loader": "^2.1.1",
    "cornerstone-web-image-loader": "^2.1.0",
    "dicom-parser": "^1.8.0",
    "hammerjs": "^2.0.8"
  }

Will you please point me to where I should insert above line of code to get this bug fixed?

**Comment by henryhe1** [comment]
Had this problem as well updating from a previous version of Cornerstone. You need to load the cornerstoneWADOImageLoaderCodecs.js and cornerstoneWADOImageLoaderWebWorker.js scripts as well if you are using the WADO loader. Then I have this at the beginning of my main script after loading dependencies:

```

cornerstoneWADOImageLoader.external.cornerstone = cornerstone;

var config = {
    webWorkerPath : 'new/js/frameworks/cornerstoneWADOImageLoaderWebWorker.js',
    taskConfiguration: {
        'decodeTask' : {
            // path of the codecs file. For some reason I have to access it differently than WebWorker even though it's at the same location? Not sure, but it works lol
            codecsPath: '../../../new/js/frameworks/cornerstoneWADOImageLoaderCodecs.js'
        }
    }
};

window.cornerstoneWADOImageLoader.webWorkerManager.initialize(config);
```

Hope that helps

**Comment by gattia** [comment]
Commenting here because this is where I ended up in my search for a solution to the same error.  This might be an obvious thing, but Im relatively new to web-dev and I stumbled on it. 

As stated by @dannyrb here: https://github.com/cornerstonejs/cornerstoneTools/issues/221#issuecomment-316212028 you have to assign the image path type (e.g., HTTP or https) to use the `cornerstoneWebImageLoader.loadImage` function. 

In trying to load images from the local disk directly into the viewer, I was using the [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) function and `readAsDataURL()` to get a URL that could be passed to cornerstone. However, the URL you get from  `FilerReader.readAsDataURL()` aren't prepended by an HTTP or https (at least not in my case?). In my case, I simply extended the solution by @dannyrb by including the following: 

`cornerstone.registerImageLoader('data', cornerstoneWebImageLoader.loadImage); `

and now it loads as expected.
