### ISSUE TITLE
metaDataProvider as fallback if image's data does not exist or is undefined

### ISSUE THREAD

**Issue by dannyrb** [chafey/cornerstoneTools#239]
metaData may not be available at the time an image is created. Would it be worth attempting `cornerstone.metaData.get()` as a fallback if the image does not contain data that tools rely on for calibration/units?

**Comment by dannyrb** [comment]
For my project, I pull in JPEG/PNG renderings, and load the DICOM tags separately via some API calls I have available to get metadata per image. The hope was/is that I could render the image, and after the fact, load/update the created image with metaData.

In modern frameworks like React or Vue, you get this for free (reactivity). I'll look into methods to achieve this outside of cornerstone for now. If I find anything cool or useful, I'll report back.

**Comment by chafey** [comment]
Hi Danny - I don't quite understand the use case here.  Are you saying you have the pixel data in advance of the metadata?  If so - can you explain how this happens?

**Comment by dannyrb** [comment]
Hi @chafey, thanks for taking the time to reply.

I'm using a modified version of the `cornerstoneWebImageLoader` to load lighter weight/compressed renderings of medical images. Often these are PNG or JPEG images not wrapped in a DICOM file. I have a separate API endpoint I can hit that provides me with DICOM tags for all of the images in a given study/series. 

There are a lot of ways to approach making sure I don't create an image until the metaDataProvider is hydrated with the right/all tags. There are also ways to customize the image loader to accommodate my unique scenario. I was mostly _curious_ about an approach that would allow metaData for a created image to change without destroying/creating a new image.

I marked my question as **closed** because I realized it is a little niche.  The particular solution I'm working on is for the veterinary field, and offers the ability to toggle between DICOM/JPEGs for different use cases (IE. JPEGs are great for mobile data limits, speed, etc. when not diagnosing).

Always happy to hear thoughts/discuss. Thanks gain for replying.

**Comment by chafey** [comment]
CornerstoneTools is designed with a few assumptions:
1) The metadata never changes
2) The metadata is available before the pixel data
These assumptions are generally true in DICOM and when followed, allows the application to setup the UI properly and stream pixel data in "on demand".  Making the pixel data viewable before the metadata will have some strange consequences on the UI - for example, the tools might need to be disabled until the metadata is loaded since they won't work properly.  I am certain my users would reject having the tools work in an inconsistent manner (disabled until metadata loaded, or even worse - work but show incorrect values until it is loaded).

**Comment by dannyrb** [comment]
I think those are good assumptions to have. In the end, I'll likely modify my image loader to make sure those assumptions are met.

Thanks again for the feedback/help.
