### ISSUE TITLE
Current versioning breaks on fresh pull downs

### ISSUE THREAD

**Issue by dannyrb** [chafey/cornerstoneTools#273]
**Problem:**
If I delete my `node_modules` folder, and run `npm install` (no dependency changes), my application no longer functions.

**Expected:**
My application should continue to function if I delete my `node_modules` folder and run `npm install`

### Why?

By default, installed dependencies use loose versioning:

* `"cornerstone-tools": "^0.9.0"`

Where the `^` symbol says grab me the [latest major version](https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json):

`^1.2.3` would match `1.X.X`, but not `2.0.0`

### Solution?

Breaking changes should be reflected in a major version bump. I believe the particular culprit for this issue is the recent "external_modules" work. (see: https://github.com/chafey/cornerstoneTools/commit/e1d2c19c27ec11dd49bc7f8980bdae975c74ba93)

**Comment by swederik** [comment]
Ah damnit you're right.

This was overlooked. I didn't consider pushing it to 1.0 since no changes were required for pages (e.g. the examples) that use script tags since the defaults are window.cornerstone and window.$ (https://github.com/chafey/cornerstoneTools/commit/e1d2c19c27ec11dd49bc7f8980bdae975c74ba93#diff-9dfb09cd4df5889c45d3aca586b6d276R4).

That means that both 0.8.5 and 0.8.6 are broken compared to previous versions for people not using script tags...

I'm open to suggestions here? Re-tag them as 1.0.0 and 1.1?

**Comment by swederik** [comment]
I've deprecated or unpublished the versions of this library / the others that introduced breaking changes. Hopefully this isn't a problem anymore.

**Comment by dannyrb** [comment]
Thanks @swederik. I'm mixed on how to best move forward with versioning. You could argue that these smaller bumps are fine as "breaking changes in Beta" are somewhat expected.

I'd probably recommend a note in the readme about using a stricter `package.json` until we're out of Beta. Maybe a bump to v1 following a switch to the OHIF org?
