### ISSUE TITLE
Typo error in function name

### ISSUE THREAD

**Issue by tartinesKiller** [chafey/cornerstoneTools#78]
Hi again!

There is a typo error at line: 
cornerstoneTools.touchmoveHandle(touchEventData, measurementData.handles.end, function() {

This causes an undef isn't a function, because the function name is touch**M**oveHandle().

By the way, the config.getTextCallback function seems undefined too (lines:
if (measurementData.annotationText === undefined) {
                config.getTextCallback(doneChangingTextCallback);
            }
)
But I don't know how to fix it

**Comment by swederik** [comment]
Ugh I swear I fixed that before. Will fix ASAP

**Comment by swederik** [comment]
Should be fixed by https://github.com/chafey/cornerstoneTools/commit/73c896ee72238d3e5b3723a4375fefb9734fb2e9

Can you check and verify? I still have some issues when both mouse and touch tools are active, though. I get errors because "panend" is firing without "panstart" or "panmove" having fired first. I don't know why yet, but the tools seem to work nonetheless.

**Comment by tartinesKiller** [comment]
Seems fixed for me, I don't use mouse and touch simultaneously so I don't have any problems. Did you change the arrow direction on purpose? It seems more logical to me! 
Anyway, thanks a lot for fixing issues so fast! ;)

**Comment by swederik** [comment]
Great! No problem, thanks for reporting the issues.

I didn't so much change it intentionally as just set the default configuration values to the same as they are in the example: https://rawgit.com/chafey/cornerstoneTools/master/examples/annotation/index.html
